version: "3"
networks:
  default:
    external:
      name: proxy
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
    ports:
      - 5601:5601
    environment:
      - VIRTUAL_HOST=kibana.*
      - SERVICE_PORTS=5601
