version: "3"
networks:
  default:
    external:
      name: proxy
services:
  portainer:
    image: portainer/portainer
    environment:
      - VIRTUAL_HOST=portainer.*
      - SERVICE_PORTS=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
